name: erddaplogs
channels:
  - conda-forge
dependencies:
        - numpy
        - cartopy
        - matplotlib
        - jupyterlab
        - requests
        - polars>=1.1.0
        - numpy
        - pre-commit
        - tqdm
        - pip
        - pip:
            - pyarrow
            - user_agents
